### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by VeritasJoker**
Finally did the PR that I promised a month ago. Fixing most issues in encoding.

A few of the issues still need testing with the newest pickling code, others should be good to go

### CODE REVIEW

**Comment by hvgazula** [comment]
approved

**Review by hvgazula — APPROVED** [review]

**Comment by hvgazula** [comment]
over to @zkokaja to approve and "merge" and not "rebase" into main

**Comment by zkokaja** [comment]
let's do a rebase again

**Comment by hvgazula** [comment]
are you really serious or just teasing us?

**Comment by hvgazula** [comment]
image

**Comment by zkokaja** [comment]
One comment: rand_emb and arb_emb functions should use a default seed and take it in as an argument. I'm okay with merging if we open a new issue for this

Nice to see documentation in the makefile on how to use the datum modifications!

**Review by zkokaja — APPROVED** [review]

**Pull request merged**
